### ISSUE TITLE
android studio 2.2rc2 使用jack compiler 编译出现的问题

### ISSUE THREAD

**Issue by Ccixyj** [netease-im/NIM_Android_UIKit#1]
**android studio 2.2rc2 使用jack compiler 编译出现的问题**

`09-09 12:51:41.657 18228-18228/com.netease.nim.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.netease.nim.demo, PID: 18228
                                                                      java.lang.IllegalAccessError: Illegal class access: 'com.netease.nimlib.sdk.NIMClient' attempting to access 'com.netease.nimlib.r.g' (declaration of 'com.netease.nimlib.sdk.NIMClient' appears in /data/app/com.netease.nim.demo-2/base.apk)
                                                                          at com.netease.nimlib.sdk.NIMClient.init(Unknown)
                                                                          at com.netease.nim.demo.NimApplication.onCreate(NimApplication.java:68)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4815)
                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:168)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:150)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5643)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)`

怎么样解决呢？

**Comment by zengbobo0805** [comment]
我现在也出现了这个，你那边解决了吗？！

**Comment by Ccixyj** [comment]
@zengbobo0805 
用kotlin了
