### ISSUE TITLE
初始化失败 “ Didn't find class "com.netease.nrtc.engine.rawapi.IRtcEngine" ”

### ISSUE THREAD

**Issue by dyguests** [netease-im/NIM_Android_UIKit#26]
AS 3.1.2
                compileSdkVersion: 26,
                buildToolsVersion: '26.0.2',
                minSdkVersion    : 15,
                targetSdkVersion : 
nim-5.0.0

调用 NIMClient.init() 时，报以下错误

```log
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/netease/nrtc/engine/rawapi/IRtcEngine;
        at com.netease.nimlib.avchat.plugin.Plugin$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.netease.nrtc.engine.rawapi.IRtcEngine" on path: DexPathList[[zip file "/data/app/com.lxt.app-1/base.apk", zip file "/data/app/com.lxt.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.lxt.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.lxt.app-1/lib/arm, /data/app/com.lxt.app-1/base.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.lxt.app-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.netease.nimlib.avchat.plugin.Plugin$1.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:776) 
```
请问有啥解决思路吗？

**Comment by dyguests** [comment]
已解决

客服说 删掉 `nim-avchat-5.0.0.jar`，就好了。

但是这是为啥啊？？

**Comment by BEspecially** [comment]
我也遇到了 删除就可以了   avchat是音视频用到的 删了不知道对功能会不会有影响呢 求解

**Comment by william198824** [comment]
我也遇到了，我是加了音视频的avchatKit才报这个异常。
