### ISSUE TITLE
加固后有些机子会闪退，不知道是不是so的问题

### ISSUE THREAD

**Issue by ywp0919** [netease-im/NIM_Android_UIKit#30]
06-26 11:18:34.438 E/art     (10421): Unexpected time out during dump checkpoint.
06-26 11:18:34.438 W/art     (10421): Attempted to destroy barrier with non zero count -1
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366] Runtime aborting...
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366] Aborting thread:
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366] "NIM-HT-MISC" prio=5 tid=32 Runnable
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   | group="" sCount=0 dsCount=0 obj=0x12c31be0 self=0x7f62dd0000
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   | sysTid=10491 nice=0 cgrp=default sched=0/0 handle=0x7f58ab4440
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   | state=R schedstat=( 64953309 27705227 86 ) utm=6 stm=0 core=5 HZ=100
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   | stack=0x7f589b2000-0x7f589b4000 stackSize=1037KB
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   | held mutexes= "abort lock" "mutator lock"(shared held)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #00 pc 0000000000489708  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+236)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #01 pc 0000000000458ac4  /system/lib64/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+220)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #02 pc 0000000000431e38  /system/lib64/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+44)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #03 pc 00000000004321b8  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+748)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #04 pc 00000000001361c4  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #05 pc 000000000053b2e0  /system/lib64/libart.so (artInvokeInterfaceTrampoline+1492)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #06 pc 000000000011d8a8  /system/lib64/libart.so (art_quick_invoke_interface_trampoline+104)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   native: #07 pc 0000000000044c38  /data/dalvik-cache/arm64/system@framework@boot.oat (Java_java_lang_Throwable__0003cinit_0003e__Ljava_lang_String_2+156)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at java.lang.Throwable.<init>(Throwable.java:95)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at java.lang.Error.<init>(Error.java:48)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:46)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at com.netease.nimlib.avchat.k.b(unavailable:-1)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at com.netease.nimlib.avchat.plugin.Plugin.a(unavailable:-1)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at com.netease.nimlib.l.b.b(unavailable:-1)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at com.netease.nimlib.b.c(unavailable:-1)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at com.netease.nimlib.b.a(unavailable:-1)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at com.netease.nimlib.b$1.run(unavailable:-1)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at android.os.Handler.handleCallback(Handler.java:815)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at android.os.Handler.dispatchMessage(Handler.java:104)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at android.os.Looper.loop(Looper.java:207)
06-26 11:18:34.439 F/art     (10421): art/runtime/runtime.cc:366]   at android.os.HandlerThread.run(HandlerThread.java:61)

06-26 11:18:37.092 W/System.err(10570): java.lang.ClassNotFoundException: Didn't find class "com.tencent.StubShell.TxMeShell" on path: DexPathList[[dex file "/data/app/com.trainor.hsehome-1/oat/arm64/base.odex", dex file "/data/app/com.trainor.hsehome-1/oat/arm64/base.odex", zip file "/data/app/com.trainor.hsehome-1/base.apk"],nativeLibraryDirectories=[/data/app/com.trainor.hsehome-1/lib/arm64, /data/app/com.trainor.hsehome-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
06-26 11:18:37.092 W/System.err(10570): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-26 11:18:37.092 W/System.err(10570): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-26 11:18:37.092 W/System.err(10570): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-26 11:18:37.092 W/System.err(10570): 	at com.tencent.StubShell.TxAppEntry.load(Native Method)
06-26 11:18:37.092 W/System.err(10570): 	at com.tencent.StubShell.TxAppEntry.a(Unknown Source)
06-26 11:18:37.092 W/System.err(10570): 	at com.tencent.StubShell.TxAppEntry.attachBaseContext(Unknown Source)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.Application.attach(Application.java:199)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1002)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.Instrumentation.newApplication(Instrumentation.java:986)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:582)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5174)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
06-26 11:18:37.092 W/System.err(10570): 	at android.os.Handler.dispatchMessage(Handler.java:111)
06-26 11:18:37.092 W/System.err(10570): 	at android.os.Looper.loop(Looper.java:207)
06-26 11:18:37.092 W/System.err(10570): 	at android.app.ActivityThread.main(ActivityThread.java:5975)
06-26 11:18:37.092 W/System.err(10570): 	at java.lang.reflect.Method.invoke(Native Method)
06-26 11:18:37.092 W/System.err(10570): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-26 11:18:37.092 W/System.err(10570): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
06-26 11:18:37.092 W/System.err(10570): 	Suppressed: java.lang.ClassNotFoundException: com.tencent.StubShell.TxMeShell
06-26 11:18:37.093 W/System.err(10570): 		at java.lang.Class.classForName(Native Method)
06-26 11:18:37.093 W/System.err(10570): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-26 11:18:37.093 W/System.err(10570): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-26 11:18:37.093 W/System.err(10570): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-26 11:18:37.093 W/System.err(10570): 		... 17 more
06-26 11:18:37.093 W/System.err(10570): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

很奇怪，应用不加固能好好的，加固后在某些特定机子上会闪退，日志只看到这些，不知道是不是这个sdk的问题，因为我项目也没有导入其他的so库了。

**Comment by NicalDai** [comment]
看着和云信的sdk和uikit没有关系诶，这个可能得你先研究一下了

**Comment by ywp0919** [comment]
这个是uikit 4.9之前的版本有问题，里面多了一个nim-avchat的jar包，但是相应的so文件没有放在uikit这里面，所以导致了这个问题，我看4.9之后的版本有把这个jar包移除掉了。

**Comment by ywp0919** [comment]
可以关掉了。
